name: MiniGameAPI
author: Allround
website: https://github.com/AllroundYT
description: A simple to use minigame api to make the creation process of minigames easier.
version: ${project.version}
api-version: 1.19
commands:
